### ISSUE TITLE
After installing Snaps, I go to the site, but nothing happens

### ISSUE THREAD

**Issue by ilyar** [sotatek-dev/mina-snap#230]
![image](https://github.com/sotatek-dev/mina-snap/assets/761285/558642fd-5295-4866-b639-98b91fe8a555)

![image](https://github.com/sotatek-dev/mina-snap/assets/761285/16c9fda8-2f11-4d2e-910a-1dfae1bfb666)

**Comment by SotaTek-TungNguyen2** [comment]
@ilyar Which snap version are you using?

**Comment by SotaTek-TungNguyen2** [comment]
Since this has been resolved. I will close this issue.
