### ISSUE TITLE
Failed to fetch snap...

### ISSUE THREAD

**Issue by U00A3** [sotatek-dev/mina-snap#236]
MetaMask 11.7.0 - mina-portal 0.1.2

Failed to fetch snap "npm:mina-portal": No matching versions of the snap are on the allowlist.

**Comment by SotaTek-TungNguyen2** [comment]
@U00A3 The issue has been fixed! Can you check again?

**Comment by SotaTek-TungNguyen2** [comment]
Since this has been resolved. I will close this issue.
